[libraries]
junit = "junit:junit:4.13.2"
ext-junit = "androidx.test.ext:junit:1.3.0"
espresso-core = "androidx.test.espresso:espresso-core:3.7.0"
appcompat = "androidx.appcompat:appcompat:1.7.1"
material = "com.google.android.material:material:1.13.0"
activity = "androidx.activity:activity:1.12.2"
constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.1"
navigation-ui = "androidx.navigation:navigation-ui:2.9.6"
navigationFragment = "androidx.navigation:navigation-fragment:2.9.6"
recyclerview = "androidx.recyclerview:recyclerview:1.4.0"
preference = "androidx.preference:preference:1.2.1"
fragment = "androidx.fragment:fragment:1.8.9"
volley = "com.android.volley:volley:1.2.1"
gson = "com.google.code.gson:gson:2.13.2"

[plugins]
android-application = "com.android.application:8.13.2"

